# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

$schema: http://azureml/sdk-2-0/CommandComponent.json
name: microsoft.com/azureml/samples://Train
version: 0.0.1
display_name: Train
type: CommandComponent
description: A dummy training module
metadata: {}
inputs:
  training_data:
    type:
    - AnyFile
    - AnyDirectory
    description: Training data organized in the torchvision format/structure
  max_epochs:
    type: Integer
    description: Maximum number of epochs for the training
  learning_rate:
    type: Float
    description: Learning rate, default is 0.01
    default: 0.01
outputs:
  model_output:
    type: AnyDirectory
    description: The output model
command:
- python
- train.py
- --training_data
- $inputPath: inputs.training_data
- --max_epochs
- $inputValue: inputs.max_epochs
- --learning_rate
- $inputValue: inputs.learning_rate
- --model_output
- $outputPath: outputs.model_output
environment:
  conda:
    conda_dependencies:
      name: project_environment
      channels:
      - defaults
      dependencies:
      - python=3.6.8
      - pip:
        - azureml-defaults
  os: Linux
